### PR TITLE
make it buildable

### PR DESCRIPTION
**Pull request by MardonHH**

### CODE REVIEW

**Comment by mikeNG** [comment]
Don't just disable the gcc wrapper. We just need to find & fix the warnings

**Comment by MardonHH** [comment]
kk
cleaner way
https://github.com/LegacyXperia/android_kernel_semc_msm7x30/pull/6

**Comment by mikeNG** [comment]
Can you message me on hangouts? I didn't find the time to mess with 7x30 & L yet. What's the status of building?

**Comment by mikeNG** [comment]
fixed

**Pull request closed without merging**
