### PR TITLE
Fixed Typo and linebreak

### PR DESCRIPTION
**Pull request by MardonHH**
reference: https://github.com/LegacyXperia/local_manifests/issues/643

### CODE REVIEW

**Comment by MardonHH** [comment]
Hmm in the other two blocks there is no linebreak for this...
thats why i removed it (lines around 245 & 287)

**Comment by mikeNG** [comment]
line breaks exist for 80 chars per line kernel rule, plus I'd like to keep close to CAF code if there's no real reason to change it

**Comment by MardonHH** [comment]
Length would be 76 and other line 78 with removed linebreak so it fits ;)
So we should submit this to caf instead?

**Comment by MardonHH** [comment]
closed because its only a cosmetic change.
Should be submitted to CAF instead

**Pull request closed without merging**
